/**
 * Centralized Error Code Catalog
 *
 * Code format: TP-XNNN
 *   TP   = TradePartners prefix
 *   X    = Category letter (A=Auth, V=Validation, W=Webhook, S=Sim, T=TradeEngine, M=MarketData, B=Billing, I=Infrastructure, K=Broker)
 *   NNN  = Sequential number within category
 *
 * Severity levels:
 *   CRITICAL - System cannot function, immediate admin intervention required
 *   HIGH     - Major feature broken, needs prompt fix
 *   MEDIUM   - Feature degraded but workaround exists
 *   LOW      - Minor issue, informational or expected user error
 */

const SEVERITY = {
  CRITICAL: 'critical',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
};

const CATEGORY = {
  AUTH: { key: 'A', label: 'Authentication & Authorization', color: '#EF4444' },
  VALIDATION: { key: 'V', label: 'Input Validation', color: '#F59E0B' },
  WEBHOOK: { key: 'W', label: 'Webhook Ingestion', color: '#8B5CF6' },
  SIM: { key: 'S', label: 'Simulation Engine', color: '#3B82F6' },
  TRADE_ENGINE: { key: 'T', label: 'Trade Decision Engine', color: '#EC4899' },
  MARKET_DATA: { key: 'M', label: 'Market Data & External Services', color: '#10B981' },
  BILLING: { key: 'B', label: 'Billing & Subscriptions', color: '#F97316' },
  INFRA: { key: 'I', label: 'Infrastructure & System', color: '#6B7280' },
  BROKER: { key: 'K', label: 'Broker Integrations', color: '#06B6D4' },
};

const ERROR_CATALOG = {
  // ═══════════════════════════════════════════════════════════════
  // AUTHENTICATION & AUTHORIZATION (TP-A)
  // ═══════════════════════════════════════════════════════════════
  'TP-A001': {
    code: 'TP-A001',
    title: 'Token Expired',
    message: 'Token expired',
    httpStatus: 401,
    severity: SEVERITY.LOW,
    category: CATEGORY.AUTH,
    description: 'The JWT authentication token has expired. Users are typically issued tokens with a limited lifespan for security.',
    possibleCauses: [
      'User session has been idle for too long',
      'Token TTL (time-to-live) is set too short',
      'Client clock skew causing premature expiration',
    ],
    suggestedFixes: [
      'User should log in again to obtain a fresh token',
      'Check JWT_EXPIRY environment variable (default is usually 24h)',
      'Ensure server and client clocks are synchronized',
      'Implement token refresh flow if not already in place',
    ],
    internalCode: 'TOKEN_EXPIRED',
  },
  'TP-A002': {
    code: 'TP-A002',
    title: 'Invalid Token',
    message: 'Invalid token',
    httpStatus: 401,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.AUTH,
    description: 'The provided JWT token is malformed, tampered with, or signed with a different secret.',
    possibleCauses: [
      'Token was modified or corrupted in transit',
      'JWT_SECRET was rotated and old tokens are no longer valid',
      'Token from a different environment (dev token on prod)',
      'Malicious token injection attempt',
    ],
    suggestedFixes: [
      'User should clear local storage and log in again',
      'Verify JWT_SECRET has not changed unexpectedly',
      'Check for CORS or proxy issues that might corrupt headers',
      'Review security logs for potential unauthorized access attempts',
    ],
    internalCode: 'INVALID_TOKEN',
  },
  'TP-A003': {
    code: 'TP-A003',
    title: 'Authentication Required',
    message: 'Please authenticate',
    httpStatus: 401,
    severity: SEVERITY.LOW,
    category: CATEGORY.AUTH,
    description: 'No authentication token was provided with the request.',
    possibleCauses: [
      'User is not logged in',
      'Token was not attached to the request header',
      'Browser cleared local storage',
    ],
    suggestedFixes: [
      'User should log in',
      'Check that the Authorization header is being set correctly',
      'Verify the API interceptor is attaching the token',
    ],
    internalCode: 'AUTH_REQUIRED',
  },
  'TP-A004': {
    code: 'TP-A004',
    title: 'Admin Access Required',
    message: 'Admin access required',
    httpStatus: 403,
    severity: SEVERITY.LOW,
    category: CATEGORY.AUTH,
    description: 'The authenticated user does not have admin privileges for this endpoint.',
    possibleCauses: [
      'Non-admin user attempted to access an admin-only route',
      'User role was downgraded but session was not refreshed',
    ],
    suggestedFixes: [
      'Ensure the user has the admin role in the database',
      'User should log out and log back in to refresh their session',
    ],
    internalCode: 'ADMIN_REQUIRED',
  },
  'TP-A005': {
    code: 'TP-A005',
    title: 'Pro Tier Required',
    message: 'This feature requires a Pro subscription',
    httpStatus: 403,
    severity: SEVERITY.LOW,
    category: CATEGORY.AUTH,
    description: 'The feature being accessed requires a Pro tier subscription.',
    possibleCauses: [
      'User is on the free tier and tried to access a Pro feature',
      'Subscription expired or was downgraded',
    ],
    suggestedFixes: [
      'User should upgrade to Pro tier via the billing page',
      'If billing is disabled (self-hosted), set user tier to pro in the database',
    ],
    internalCode: 'PRO_REQUIRED',
  },
  'TP-A006': {
    code: 'TP-A006',
    title: 'Invalid OAuth Authorization Code',
    message: 'Invalid authorization code',
    httpStatus: 400,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.AUTH,
    description: 'The OAuth2 authorization code provided is invalid, already used, or expired.',
    possibleCauses: [
      'Authorization code was already exchanged for a token',
      'Code has expired (codes are short-lived)',
      'Redirect URI mismatch between authorize and token requests',
      'Invalid PKCE code verifier',
    ],
    suggestedFixes: [
      'Initiate a new OAuth2 authorization flow',
      'Ensure redirect_uri matches exactly between authorize and token requests',
      'Verify PKCE code_challenge and code_verifier are computed correctly',
    ],
    internalCode: 'INVALID_AUTH_CODE',
  },
  'TP-A007': {
    code: 'TP-A007',
    title: 'Invalid Refresh Token',
    message: 'Invalid refresh token',
    httpStatus: 401,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.AUTH,
    description: 'The OAuth2 refresh token is invalid or has been revoked.',
    possibleCauses: [
      'Refresh token was revoked',
      'Token has expired',
      'Token was already used (one-time rotation)',
    ],
    suggestedFixes: [
      'Re-authenticate through the OAuth2 authorization flow',
      'Check that refresh tokens are being stored securely',
    ],
    internalCode: 'INVALID_REFRESH_TOKEN',
  },

  // ═══════════════════════════════════════════════════════════════
  // INPUT VALIDATION (TP-V)
  // ═══════════════════════════════════════════════════════════════
  'TP-V001': {
    code: 'TP-V001',
    title: 'Validation Error',
    message: 'Validation Error',
    httpStatus: 400,
    severity: SEVERITY.LOW,
    category: CATEGORY.VALIDATION,
    description: 'One or more request fields failed validation. The response details field contains specifics.',
    possibleCauses: [
      'Required fields are missing',
      'Field values are out of acceptable range',
      'Incorrect data types submitted',
    ],
    suggestedFixes: [
      'Check the "details" field in the error response for specific field errors',
      'Refer to the API documentation for required fields and formats',
    ],
    internalCode: 'VALIDATION_ERROR',
  },
  'TP-V002': {
    code: 'TP-V002',
    title: 'Resource Already Exists',
    message: 'Resource already exists',
    httpStatus: 409,
    severity: SEVERITY.LOW,
    category: CATEGORY.VALIDATION,
    description: 'A unique constraint violation occurred. A record with the same unique key already exists.',
    possibleCauses: [
      'Duplicate email or username during registration',
      'Duplicate trade entry',
      'Duplicate holding for the same symbol',
      'Duplicate API key name',
    ],
    suggestedFixes: [
      'Use a different value for the conflicting unique field',
      'Check if the record already exists before creating',
    ],
    internalCode: 'DUPLICATE_RESOURCE',
  },
  'TP-V003': {
    code: 'TP-V003',
    title: 'Invalid Reference',
    message: 'Invalid reference',
    httpStatus: 400,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.VALIDATION,
    description: 'A foreign key constraint violation occurred. The referenced record does not exist.',
    possibleCauses: [
      'Referencing a deleted user, account, or trade',
      'Invalid account_id or user_id in a request',
      'Data integrity issue from a failed migration',
    ],
    suggestedFixes: [
      'Verify the referenced resource still exists',
      'Check database integrity with admin tools',
      'Run pending migrations if the schema is out of date',
    ],
    internalCode: 'INVALID_REFERENCE',
  },
  'TP-V004': {
    code: 'TP-V004',
    title: 'Invalid JSON Payload',
    message: 'Invalid JSON payload',
    httpStatus: 400,
    severity: SEVERITY.LOW,
    category: CATEGORY.VALIDATION,
    description: 'The request body could not be parsed as valid JSON.',
    possibleCauses: [
      'Malformed JSON syntax in the request body',
      'Wrong Content-Type header (not application/json)',
      'Truncated request due to network issues',
    ],
    suggestedFixes: [
      'Validate JSON syntax before sending',
      'Set Content-Type header to application/json',
      'Check for network issues that might truncate the request',
    ],
    internalCode: 'INVALID_JSON',
  },
  'TP-V005': {
    code: 'TP-V005',
    title: 'Entry Time Required',
    message: 'Entry time is required for creating a trade',
    httpStatus: 400,
    severity: SEVERITY.LOW,
    category: CATEGORY.VALIDATION,
    description: 'A trade record cannot be created without an entry timestamp.',
    possibleCauses: [
      'Missing entry_time field in the trade creation request',
      'CSV import row is missing the date/time column',
    ],
    suggestedFixes: [
      'Include the entry_time field in the request body',
      'Verify CSV mapping includes a date/time column',
    ],
    internalCode: 'ENTRY_TIME_REQUIRED',
  },
  'TP-V006': {
    code: 'TP-V006',
    title: 'Resource Not Found',
    message: 'Not found',
    httpStatus: 404,
    severity: SEVERITY.LOW,
    category: CATEGORY.VALIDATION,
    description: 'The requested resource could not be found.',
    possibleCauses: [
      'The resource was deleted',
      'Invalid or non-existent ID in the URL',
      'Route path is incorrect',
    ],
    suggestedFixes: [
      'Verify the resource ID is correct',
      'Check if the resource was recently deleted',
    ],
    internalCode: 'NOT_FOUND',
  },
  'TP-V007': {
    code: 'TP-V007',
    title: 'Account Not Found',
    message: 'Account not found',
    httpStatus: 404,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.VALIDATION,
    description: 'The specified trading account does not exist or the user does not have access.',
    possibleCauses: [
      'Account was deleted',
      'Using an account ID from a different user',
      'Account ID is malformed',
    ],
    suggestedFixes: [
      'Verify the account ID in the accounts list',
      'Ensure the account belongs to the authenticated user',
    ],
    internalCode: 'ACCOUNT_NOT_FOUND',
  },

  // ═══════════════════════════════════════════════════════════════
  // WEBHOOK INGESTION (TP-W)
  // ═══════════════════════════════════════════════════════════════
  'TP-W001': {
    code: 'TP-W001',
    title: 'Webhook Authentication Failed',
    message: 'No valid user identity. Provide a JWT token or x-api-key header.',
    httpStatus: 401,
    severity: SEVERITY.HIGH,
    category: CATEGORY.WEBHOOK,
    description: 'The incoming webhook request has no valid authentication. All non-PING webhooks require either a JWT token or an API key.',
    possibleCauses: [
      'TradingView alert is not configured with an API key',
      'API key has been revoked or deleted',
      'JWT token is missing from the webhook headers',
      'SIM_DEFAULT_USER_ID is not set and no credentials were provided',
    ],
    suggestedFixes: [
      'Add x-api-key header to the webhook source configuration',
      'Generate a new API key from Settings > API Keys',
      'Set the SIM_DEFAULT_USER_ID environment variable for unauthenticated webhooks',
      'Verify the API key is active and has not been revoked',
    ],
    internalCode: 'WEBHOOK_AUTH_FAILED',
  },
  'TP-W002': {
    code: 'TP-W002',
    title: 'Invalid HMAC Signature',
    message: 'Invalid HMAC signature',
    httpStatus: 422,
    severity: SEVERITY.HIGH,
    category: CATEGORY.WEBHOOK,
    description: 'The webhook payload HMAC signature did not match. This could indicate tampering or misconfiguration.',
    possibleCauses: [
      'WEBHOOK_SECRET on the server does not match the secret used to sign the payload',
      'Payload was modified in transit (proxy rewriting, encoding changes)',
      'Wrong hashing algorithm used by the sender',
    ],
    suggestedFixes: [
      'Verify WEBHOOK_SECRET matches between sender and receiver',
      'Check that no proxies are modifying the request body',
      'Ensure the signature is computed over the raw body, not parsed JSON',
    ],
    internalCode: 'INVALID_HMAC',
  },
  'TP-W003': {
    code: 'TP-W003',
    title: 'Webhook Payload Too Old',
    message: 'Payload too old',
    httpStatus: 422,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.WEBHOOK,
    description: 'The webhook payload timestamp exceeds the maximum allowed age. Stale signals are rejected to prevent acting on outdated data.',
    possibleCauses: [
      'Network latency delayed delivery beyond the threshold',
      'TradingView alert was queued and delivered late',
      'Sender system clock is significantly behind',
    ],
    suggestedFixes: [
      'Increase WEBHOOK_MAX_AGE_SECONDS if legitimate signals arrive late',
      'Check network connectivity between the webhook source and the server',
      'Verify the sender system clock is synchronized (NTP)',
    ],
    internalCode: 'PAYLOAD_TOO_OLD',
  },
  'TP-W004': {
    code: 'TP-W004',
    title: 'Webhook Payload From Future',
    message: 'Payload timestamp is in the future',
    httpStatus: 422,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.WEBHOOK,
    description: 'The webhook payload timestamp is in the future relative to the server clock.',
    possibleCauses: [
      'Sender system clock is ahead of the server',
      'Time zone misconfiguration',
    ],
    suggestedFixes: [
      'Synchronize clocks on both sender and server using NTP',
      'Ensure timestamps use UTC',
    ],
    internalCode: 'PAYLOAD_FUTURE_TIMESTAMP',
  },
  'TP-W005': {
    code: 'TP-W005',
    title: 'Invalid Webhook Timestamp',
    message: 'Invalid timestamp format',
    httpStatus: 422,
    severity: SEVERITY.LOW,
    category: CATEGORY.WEBHOOK,
    description: 'The timestamp field in the webhook payload is not in a recognized format.',
    possibleCauses: [
      'Non-standard timestamp format used',
      'Timestamp field is missing or null',
    ],
    suggestedFixes: [
      'Use ISO 8601 format (e.g., 2024-01-15T14:30:00Z) or Unix epoch seconds',
      'Ensure the timestamp field is present in the payload',
    ],
    internalCode: 'INVALID_TIMESTAMP',
  },
  'TP-W006': {
    code: 'TP-W006',
    title: 'Invalid Webhook Payload',
    message: 'Payload must be a JSON object',
    httpStatus: 422,
    severity: SEVERITY.LOW,
    category: CATEGORY.WEBHOOK,
    description: 'The webhook payload is not a valid JSON object. It may be a string, array, null, or otherwise malformed.',
    possibleCauses: [
      'TradingView alert message is plain text instead of JSON',
      'Webhook source is sending a non-JSON content type',
    ],
    suggestedFixes: [
      'Format the TradingView alert message as a JSON object: {"ticker": "{{ticker}}", "action": "buy", ...}',
      'Ensure Content-Type is application/json',
    ],
    internalCode: 'INVALID_PAYLOAD_FORMAT',
  },
  'TP-W007': {
    code: 'TP-W007',
    title: 'Missing Symbol in Webhook',
    message: 'Missing required field: ticker or symbol',
    httpStatus: 422,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.WEBHOOK,
    description: 'The webhook payload does not contain a ticker/symbol field, which is required to identify the instrument.',
    possibleCauses: [
      'TradingView alert message template is missing the {{ticker}} variable',
      'Field name mismatch (using "instrument" instead of "ticker" or "symbol")',
    ],
    suggestedFixes: [
      'Add "ticker": "{{ticker}}" or "symbol": "{{ticker}}" to the alert JSON',
      'Check the webhook payload format documentation',
    ],
    internalCode: 'MISSING_SYMBOL',
  },
  'TP-W008': {
    code: 'TP-W008',
    title: 'Missing Action in Webhook',
    message: 'Missing required field: action or order_action',
    httpStatus: 422,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.WEBHOOK,
    description: 'The webhook payload does not specify a trade action (buy, sell, close).',
    possibleCauses: [
      'TradingView alert message template is missing the action field',
      'Using a non-standard field name for the action',
    ],
    suggestedFixes: [
      'Add "action": "buy" or "action": "sell" to the alert JSON',
      'Valid actions are: buy, sell, close (case-insensitive)',
    ],
    internalCode: 'MISSING_ACTION',
  },
  'TP-W009': {
    code: 'TP-W009',
    title: 'Invalid Action in Webhook',
    message: 'Invalid action. Must be one of: buy, sell, close',
    httpStatus: 422,
    severity: SEVERITY.LOW,
    category: CATEGORY.WEBHOOK,
    description: 'The action field in the webhook payload contains an unrecognized value.',
    possibleCauses: [
      'Typo in the action field (e.g., "buuy" instead of "buy")',
      'Using broker-specific action names',
    ],
    suggestedFixes: [
      'Use one of the supported actions: buy, sell, close (case-insensitive)',
    ],
    internalCode: 'INVALID_ACTION',
  },
  'TP-W010': {
    code: 'TP-W010',
    title: 'Missing Price Data in Webhook',
    message: 'Missing or invalid price',
    httpStatus: 422,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.WEBHOOK,
    description: 'A price tick webhook is missing the required price field or the price is not a valid number.',
    possibleCauses: [
      'Price field omitted from the payload',
      'Price is a string instead of a number',
      'Price is zero or negative',
    ],
    suggestedFixes: [
      'Include a numeric "price" field in the price tick payload',
      'Ensure the price is a positive number',
    ],
    internalCode: 'MISSING_PRICE',
  },
  'TP-W011': {
    code: 'TP-W011',
    title: 'Internal Webhook Processing Error',
    message: 'Internal webhook processing error',
    httpStatus: 500,
    severity: SEVERITY.HIGH,
    category: CATEGORY.WEBHOOK,
    description: 'An unexpected error occurred while processing the incoming webhook. The signal was received but could not be stored or routed.',
    possibleCauses: [
      'Database connection failure',
      'Schema mismatch (missing webhook_events table)',
      'Memory pressure or server resource exhaustion',
    ],
    suggestedFixes: [
      'Check server logs for the specific error stack trace',
      'Verify database connectivity (check /api/health)',
      'Run pending database migrations',
      'Check server memory and CPU usage',
    ],
    internalCode: 'WEBHOOK_PROCESSING_ERROR',
  },

  // ═══════════════════════════════════════════════════════════════
  // SIMULATION ENGINE (TP-S)
  // ═══════════════════════════════════════════════════════════════
  'TP-S001': {
    code: 'TP-S001',
    title: 'Kill Switch Active',
    message: 'Kill switch is active -- all orders rejected',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.SIM,
    description: 'The simulation account kill switch is enabled. All new orders are automatically rejected.',
    possibleCauses: [
      'Admin or user manually activated the kill switch',
      'Daily loss limit triggered automatic kill switch activation',
    ],
    suggestedFixes: [
      'Toggle the kill switch off via the Simulation dashboard',
      'Review daily P&L to understand why the kill switch was triggered',
      'Adjust daily loss limit thresholds if they are too conservative',
    ],
    internalCode: 'KILL_SWITCH_ACTIVE',
  },
  'TP-S002': {
    code: 'TP-S002',
    title: 'No Price Data Available',
    message: 'No price data available — send a price tick or include bid/ask/mid in the signal',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.SIM,
    description: 'The executor cannot determine a fill price for the order. No recent price ticks, quotes, or bid/ask data is available for the symbol.',
    possibleCauses: [
      'No price tick webhooks have been sent for this symbol',
      'Price data in the global market state has expired',
      'Data service is down or the symbol is not being tracked',
      'The signal payload did not include bid/ask/mid fields',
    ],
    suggestedFixes: [
      'Send a price tick webhook before trading signals',
      'Include bid, ask, or mid price fields in the signal payload',
      'Verify the data service is running and returning quotes for this symbol',
      'Check the Global Market State health endpoint',
    ],
    internalCode: 'NO_PRICE_DATA',
  },
  'TP-S003': {
    code: 'TP-S003',
    title: 'Insufficient Buying Power',
    message: 'Insufficient buying power',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.SIM,
    description: 'The simulated account does not have enough buying power to execute this order.',
    possibleCauses: [
      'Account balance is too low for the position size',
      'Too many open positions consuming buying power',
      'Commission costs push the total above available balance',
    ],
    suggestedFixes: [
      'Close some existing positions to free up buying power',
      'Reset the sim account with a higher starting balance',
      'Reduce position sizing in the strategy configuration',
    ],
    internalCode: 'INSUFFICIENT_BUYING_POWER',
  },
  'TP-S004': {
    code: 'TP-S004',
    title: 'Duplicate Position',
    message: 'Duplicate position — already open',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.SIM,
    description: 'An order was rejected because an identical position (same symbol/contract) is already open.',
    possibleCauses: [
      'Duplicate webhook signals sent in quick succession',
      'Strategy is sending redundant entry signals',
    ],
    suggestedFixes: [
      'Add deduplication logic to the signal source',
      'Check the open positions list before sending new signals',
      'This is expected behavior — the system prevents accidental double entries',
    ],
    internalCode: 'DUPLICATE_POSITION',
  },
  'TP-S005': {
    code: 'TP-S005',
    title: 'No Sim Account State',
    message: 'No sim account state found. Initialize account first.',
    httpStatus: 500,
    severity: SEVERITY.HIGH,
    category: CATEGORY.SIM,
    description: 'The simulation engine could not find account state for the user. The sim account needs to be initialized before processing trades.',
    possibleCauses: [
      'User has never initialized their sim account',
      'Account state was deleted or corrupted',
      'Database migration for sim tables has not been run',
    ],
    suggestedFixes: [
      'Navigate to the Simulation dashboard to auto-initialize the account',
      'Call the POST /api/sim/account/reset endpoint to create fresh state',
      'Run pending database migrations',
    ],
    internalCode: 'NO_SIM_ACCOUNT',
  },
  'TP-S006': {
    code: 'TP-S006',
    title: 'No Open Position to Close',
    message: 'No open position to close',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.SIM,
    description: 'A sell/close order was received but no matching open position exists.',
    possibleCauses: [
      'Position was already closed by a stop-loss or take-profit exit',
      'The exit monitor closed the position before the manual close signal arrived',
      'Symbol mismatch between open and close signals',
    ],
    suggestedFixes: [
      'Check the sim trades list to confirm the position status',
      'Verify the symbol in the close signal matches the open position exactly',
    ],
    internalCode: 'NO_OPEN_POSITION',
  },
  'TP-S007': {
    code: 'TP-S007',
    title: 'Position Already Closed',
    message: 'Position is no longer OPEN (already closed)',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.SIM,
    description: 'The position was already closed when the close/exit attempt was made.',
    possibleCauses: [
      'Race condition between exit monitor and manual close',
      'Multiple exit signals arriving for the same position',
    ],
    suggestedFixes: [
      'This is generally benign — the position was already closed successfully',
      'Review exit monitor settings to reduce overlap with manual exits',
    ],
    internalCode: 'POSITION_ALREADY_CLOSED',
  },
  'TP-S008': {
    code: 'TP-S008',
    title: 'Replay No Historical Data',
    message: 'No historical data available for the specified range',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.SIM,
    description: 'A strategy replay could not proceed because no candle/price data is available for the specified symbol and date range.',
    possibleCauses: [
      'Symbol is not covered by the configured data provider',
      'Date range falls on weekends/holidays with no trading',
      'Data provider API key is missing or rate-limited',
    ],
    suggestedFixes: [
      'Verify the symbol is valid and supported by Finnhub/Alpha Vantage',
      'Adjust the date range to include trading days',
      'Check data provider API key configuration',
    ],
    internalCode: 'REPLAY_NO_DATA',
  },
  'TP-S009': {
    code: 'TP-S009',
    title: 'Batch Duplicate Entry',
    message: 'Batch dedup: entry already executed',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.SIM,
    description: 'During batch processing, a duplicate entry was detected and skipped.',
    possibleCauses: [
      'Multiple identical signals in the same processing batch',
      'Signal was resubmitted while still being processed',
    ],
    suggestedFixes: [
      'This is expected defensive behavior — no action needed',
      'Review signal source for unnecessary duplicates to reduce noise',
    ],
    internalCode: 'BATCH_DEDUP',
  },
  'TP-S010': {
    code: 'TP-S010',
    title: 'Insufficient Trades for Calibration',
    message: 'Insufficient trades for calibration (min 10)',
    httpStatus: 400,
    severity: SEVERITY.LOW,
    category: CATEGORY.SIM,
    description: 'Adaptive intelligence calibration requires at least 10 completed trades to generate meaningful insights.',
    possibleCauses: [
      'Simulation has just started and fewer than 10 trades have been completed',
    ],
    suggestedFixes: [
      'Continue running the simulation until at least 10 trades complete',
      'Run a strategy replay to generate historical trade data faster',
    ],
    internalCode: 'INSUFFICIENT_TRADES_CALIBRATION',
  },
  'TP-S011': {
    code: 'TP-S011',
    title: 'Insufficient AI Credits',
    message: 'Insufficient credits for AI insights',
    httpStatus: 402,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.SIM,
    description: 'The user does not have enough AI credits to generate adaptive intelligence insights.',
    possibleCauses: [
      'AI credit balance has been exhausted',
      'No credit allocation was set up',
    ],
    suggestedFixes: [
      'Purchase additional AI credits via the billing page',
      'Wait for the monthly credit refresh',
      'Use local AI providers (Ollama) to avoid credit costs',
    ],
    internalCode: 'INSUFFICIENT_AI_CREDITS',
  },

  // ═══════════════════════════════════════════════════════════════
  // TRADE DECISION ENGINE (TP-T)
  // ═══════════════════════════════════════════════════════════════
  'TP-T001': {
    code: 'TP-T001',
    title: 'Fail-Closed: No Valid Contracts',
    message: 'FAIL_CLOSED: Chain data present but no valid contracts',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.TRADE_ENGINE,
    description: 'Options chain data was received but contained no contracts meeting minimum liquidity/spread requirements.',
    possibleCauses: [
      'Underlying symbol has very low options volume',
      'All available strikes have spreads exceeding the maximum threshold',
      'Chain data is for an incorrect expiration date',
    ],
    suggestedFixes: [
      'Review bid-ask spread thresholds in the trade decision engine configuration',
      'Consider trading more liquid underlyings',
      'Verify the chain data source is returning correct expirations',
    ],
    internalCode: 'FAIL_CLOSED_NO_CONTRACTS',
  },
  'TP-T002': {
    code: 'TP-T002',
    title: 'Fail-Closed: No Chain Data',
    message: 'FAIL_CLOSED: No chain data received — cannot validate options liquidity',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The trade decision engine requires options chain data to validate liquidity, but no chain data was available.',
    possibleCauses: [
      'Data service is not returning chain data for this symbol',
      'Chain data webhook has not been sent',
      'Global Market State cache has expired for this symbol',
    ],
    suggestedFixes: [
      'Verify the data service is configured to poll chains for this symbol',
      'Send a chain_snapshot webhook before the trade signal',
      'Check the Global Market State health endpoint',
    ],
    internalCode: 'FAIL_CLOSED_NO_CHAIN',
  },
  'TP-T003': {
    code: 'TP-T003',
    title: 'Fail-Closed: Stale Chain Data',
    message: 'FAIL_CLOSED: Chain data stale',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.TRADE_ENGINE,
    description: 'Options chain data is too old to make reliable trading decisions. The data exceeds the configured staleness threshold.',
    possibleCauses: [
      'Market data polling interval is too long',
      'Data service had a temporary outage',
      'Signal arrived outside market hours when data is not refreshed',
    ],
    suggestedFixes: [
      'Reduce GMS_POLL_INTERVAL_MS for more frequent data refreshes',
      'Ensure the data service is actively polling during market hours',
      'Wait for fresh data before retrying',
    ],
    internalCode: 'FAIL_CLOSED_STALE_CHAIN',
  },
  'TP-T004': {
    code: 'TP-T004',
    title: 'Fail-Closed: Stale Macro Bias',
    message: 'FAIL_CLOSED: Macro bias severely stale',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.TRADE_ENGINE,
    description: 'Macro market bias data (e.g., SPY trend, VIX) has not been updated within the required timeframe.',
    possibleCauses: [
      'Trend data scheduler is not running',
      'Data service API keys are expired or rate-limited',
      'Market is closed and no fresh macro data is available',
    ],
    suggestedFixes: [
      'Check that ENABLE_TREND_SCHEDULER is not set to false',
      'Verify data provider API keys (Finnhub, Alpha Vantage)',
      'Check the trend data scheduler logs for errors',
    ],
    internalCode: 'FAIL_CLOSED_STALE_MACRO',
  },
  'TP-T005': {
    code: 'TP-T005',
    title: 'Fail-Closed: Stale Trend Data',
    message: 'FAIL_CLOSED: Trend data severely stale',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.TRADE_ENGINE,
    description: 'Per-symbol trend/EMA data has not been updated within the required timeframe.',
    possibleCauses: [
      'Trend data scheduler is not running or has crashed',
      'Data provider rate limits preventing fresh data fetches',
    ],
    suggestedFixes: [
      'Restart the trend data scheduler',
      'Check data provider API usage/limits',
    ],
    internalCode: 'FAIL_CLOSED_STALE_TREND',
  },
  'TP-T006': {
    code: 'TP-T006',
    title: 'Fail-Closed: Bid-Ask Spread Too Wide',
    message: 'FAIL_CLOSED: Bid-ask spread exceeds maximum',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The bid-ask spread on the selected option contract exceeds the configured maximum percentage, indicating poor liquidity.',
    possibleCauses: [
      'Low-volume option contract selected',
      'Market is in pre/post-market hours with wider spreads',
      'Underlying stock has low overall options volume',
    ],
    suggestedFixes: [
      'Trade during regular market hours for tighter spreads',
      'Select more liquid strikes (closer to ATM)',
      'Adjust the maximum spread threshold if acceptable for the strategy',
    ],
    internalCode: 'FAIL_CLOSED_SPREAD_TOO_WIDE',
  },
  'TP-T007': {
    code: 'TP-T007',
    title: 'Fail-Closed: Daily Loss Limit',
    message: 'FAIL_CLOSED: Daily loss limit reached',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.SIM,
    description: 'The simulated account has reached the configured daily loss limit. No new entries are allowed until the next trading day.',
    possibleCauses: [
      'Multiple losing trades in the current session',
      'Daily loss limit is set too conservatively',
    ],
    suggestedFixes: [
      'Wait until the next trading day (daily loss resets)',
      'Review the daily loss limit setting in the sim configuration',
      'Analyze losing trades to identify systematic issues',
    ],
    internalCode: 'DAILY_LOSS_LIMIT',
  },
  'TP-T008': {
    code: 'TP-T008',
    title: 'Fail-Closed: Macro/Local Bias Mismatch',
    message: 'FAIL_CLOSED: Macro/local bias mismatch too severe',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The macro market bias (e.g., SPY bearish) conflicts with the local signal direction (e.g., bullish entry). The conflict score exceeds the threshold.',
    possibleCauses: [
      'Market regime shift — broad market is moving against the trade direction',
      'Stale macro data showing an outdated bias',
    ],
    suggestedFixes: [
      'Review macro vs. local bias alignment',
      'Refresh macro/trend data',
      'Adjust the bias mismatch threshold if the strategy tolerates more divergence',
    ],
    internalCode: 'FAIL_CLOSED_BIAS_MISMATCH',
  },
  'TP-T009': {
    code: 'TP-T009',
    title: 'Precondition Failure: No Entry Signal',
    message: 'PRECONDITION_FAIL: No entry signal in state',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The trade decision engine expected an entry signal in the pipeline state, but none was found.',
    possibleCauses: [
      'Signal was filtered or consumed by an earlier gate',
      'Webhook payload was processed but the action was not recognized as an entry',
    ],
    suggestedFixes: [
      'Check the webhook event log for the signal status',
      'Verify the action field is "buy" for entries',
    ],
    internalCode: 'PRECONDITION_NO_SIGNAL',
  },
  'TP-T010': {
    code: 'TP-T010',
    title: 'Conviction Score Too Low',
    message: 'CONVICTION_FAIL: Score below minimum threshold',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The computed conviction score for this trade is below the minimum threshold (40). Trades with low conviction are blocked to protect capital.',
    possibleCauses: [
      'Weak signal confluence — not enough confirming indicators',
      'Market conditions are unfavorable for the strategy',
      'Missing data inputs that would increase conviction',
    ],
    suggestedFixes: [
      'Review the conviction scoring formula and weights',
      'Ensure all data inputs (flow, price action, trend) are available',
      'Wait for higher-conviction setups',
    ],
    internalCode: 'CONVICTION_TOO_LOW',
  },
  'TP-T011': {
    code: 'TP-T011',
    title: 'Options Construction Failed',
    message: 'Cannot determine direction or no recipe found',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The options constructor could not build a contract for this trade. Either the direction could not be determined from the signal, or no recipe exists for the strategy/direction combination.',
    possibleCauses: [
      'Signal is ambiguous — neither clearly bullish nor bearish',
      'Strategy does not have an options recipe defined',
      'Options chain is unavailable for the symbol',
    ],
    suggestedFixes: [
      'Verify strategy recipes are configured in the options constructor',
      'Ensure signals include clear directional information',
      'Check that options chain data is available for the symbol',
    ],
    internalCode: 'OPTIONS_CONSTRUCTION_FAILED',
  },
  'TP-T012': {
    code: 'TP-T012',
    title: 'Safety Guard: Trading Hours',
    message: 'Trade rejected: outside allowed trading hours',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.TRADE_ENGINE,
    description: 'A trade signal was received outside the configured trading hours window.',
    possibleCauses: [
      'Signal arrived during pre/post-market or overnight',
      'Trading hours configuration is too restrictive',
    ],
    suggestedFixes: [
      'Wait for regular trading hours',
      'Adjust the allowed trading hours window in the strategy configuration',
    ],
    internalCode: 'OUTSIDE_TRADING_HOURS',
  },
  'TP-T013': {
    code: 'TP-T013',
    title: 'Safety Guard: Max Positions',
    message: 'Maximum open positions limit reached',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The maximum number of simultaneous open positions has been reached. New entries are blocked until existing positions are closed.',
    possibleCauses: [
      'All position slots are occupied',
      'Max positions limit is set too low',
    ],
    suggestedFixes: [
      'Close existing positions to free up slots',
      'Increase the max positions limit if appropriate for the strategy',
    ],
    internalCode: 'MAX_POSITIONS_REACHED',
  },
  'TP-T014': {
    code: 'TP-T014',
    title: 'Entry Cooldown Active',
    message: 'Entry cooldown period has not elapsed',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The minimum time between entries has not elapsed since the last trade entry.',
    possibleCauses: [
      'Rapid-fire signals arriving faster than the cooldown allows',
    ],
    suggestedFixes: [
      'Wait for the cooldown period to expire',
      'Adjust the entry cooldown setting if shorter intervals are acceptable',
    ],
    internalCode: 'ENTRY_COOLDOWN',
  },
  'TP-T015': {
    code: 'TP-T015',
    title: 'Strategy Suppressed',
    message: 'Strategy is currently suppressed or blocked',
    httpStatus: null,
    severity: SEVERITY.LOW,
    category: CATEGORY.TRADE_ENGINE,
    description: 'The specific strategy that generated this signal has been suppressed by the adaptive intelligence system based on recent performance.',
    possibleCauses: [
      'Strategy has been losing consistently and was auto-suppressed',
      'Admin manually suppressed the strategy',
    ],
    suggestedFixes: [
      'Review the strategy performance in the Intelligence Dashboard',
      'Manually re-enable the strategy if the suppression is no longer warranted',
      'Wait for the adaptive system to auto-reinstate after performance improves',
    ],
    internalCode: 'STRATEGY_SUPPRESSED',
  },

  // ═══════════════════════════════════════════════════════════════
  // MARKET DATA & EXTERNAL SERVICES (TP-M)
  // ═══════════════════════════════════════════════════════════════
  'TP-M001': {
    code: 'TP-M001',
    title: 'Data Service Unreachable',
    message: 'Data service unreachable — connectivity gate UNHEALTHY',
    httpStatus: 503,
    severity: SEVERITY.CRITICAL,
    category: CATEGORY.MARKET_DATA,
    description: 'The connectivity gate has marked the data service as unreachable after consecutive health probe failures. Requests are blocked until the probe succeeds or a manual reset is performed.',
    possibleCauses: [
      'Data service is down or unreachable',
      'Network connectivity issues between backend and data service',
      'Data service API key is invalid',
      'Data service is overloaded',
    ],
    suggestedFixes: [
      'Check DATA_SERVICE_URL environment variable is correct',
      'Verify the data service is running and healthy',
      'Check network connectivity (firewall, DNS, VPN)',
      'POST /api/sim/connectivity/reset to force recovery',
      'Probe runs every 30s — gate will auto-recover when data-service responds',
    ],
    internalCode: 'CONNECTIVITY_GATE_UNHEALTHY',
  },
  'TP-M002': {
    code: 'TP-M002',
    title: 'Finnhub API Key Not Configured',
    message: 'Finnhub API key not configured',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.MARKET_DATA,
    description: 'The FINNHUB_API_KEY environment variable is not set. Finnhub is the primary market data provider.',
    possibleCauses: [
      'FINNHUB_API_KEY not set in .env or environment',
      'Environment variables not loaded properly',
    ],
    suggestedFixes: [
      'Sign up for a Finnhub API key at finnhub.io',
      'Add FINNHUB_API_KEY to your .env file',
      'Restart the server after adding the key',
    ],
    internalCode: 'FINNHUB_NOT_CONFIGURED',
  },
  'TP-M003': {
    code: 'TP-M003',
    title: 'Finnhub Rate Limit Exceeded',
    message: 'Finnhub API rate limit exceeded',
    httpStatus: 429,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.MARKET_DATA,
    description: 'Too many requests have been sent to the Finnhub API within the rate limit window.',
    possibleCauses: [
      'High request volume from multiple users',
      'Free tier API key with low rate limits',
      'Background jobs (enrichment, scanner) consuming the quota',
    ],
    suggestedFixes: [
      'Upgrade to a Finnhub premium API key for higher limits',
      'Reduce the frequency of background data polling',
      'Implement request batching or caching',
    ],
    internalCode: 'FINNHUB_RATE_LIMITED',
  },
  'TP-M004': {
    code: 'TP-M004',
    title: 'Finnhub Server Error',
    message: 'Finnhub API server error (retry failed)',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.MARKET_DATA,
    description: 'Finnhub returned a 502/503/504 error and automatic retries were exhausted.',
    possibleCauses: [
      'Finnhub is experiencing an outage',
      'Temporary server issues on Finnhub side',
    ],
    suggestedFixes: [
      'Check Finnhub status page for known outages',
      'The system will automatically retry — wait and check again',
      'Alpha Vantage will be used as a fallback if configured',
    ],
    internalCode: 'FINNHUB_SERVER_ERROR',
  },
  'TP-M005': {
    code: 'TP-M005',
    title: 'Alpha Vantage Daily Limit Reached',
    message: 'Alpha Vantage daily API limit reached (25 calls). Try again tomorrow.',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.MARKET_DATA,
    description: 'The free-tier Alpha Vantage API allows only 25 requests per day. The daily limit has been reached.',
    possibleCauses: [
      'Using a free-tier Alpha Vantage API key',
      'Many symbols needed data enrichment today',
    ],
    suggestedFixes: [
      'Upgrade to a premium Alpha Vantage API key',
      'Wait until tomorrow for the limit to reset',
      'Reduce the number of symbols requiring Alpha Vantage data',
    ],
    internalCode: 'ALPHA_VANTAGE_DAILY_LIMIT',
  },
  'TP-M006': {
    code: 'TP-M006',
    title: 'Alpha Vantage API Key Not Configured',
    message: 'Alpha Vantage API key not configured',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.MARKET_DATA,
    description: 'The ALPHA_VANTAGE_API_KEY environment variable is not set. Alpha Vantage is used as a fallback data provider.',
    possibleCauses: [
      'ALPHA_VANTAGE_API_KEY not set in .env',
    ],
    suggestedFixes: [
      'Sign up for an Alpha Vantage API key at alphavantage.co',
      'Add ALPHA_VANTAGE_API_KEY to your .env file',
    ],
    internalCode: 'ALPHA_VANTAGE_NOT_CONFIGURED',
  },
  'TP-M007': {
    code: 'TP-M007',
    title: 'Databento API Key Not Configured',
    message: 'Databento API key not configured',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.MARKET_DATA,
    description: 'The DATABENTO_API_KEY environment variable is not set. Databento is used for CME futures data.',
    possibleCauses: [
      'DATABENTO_API_KEY not set in .env',
    ],
    suggestedFixes: [
      'Sign up for a Databento API key at databento.com',
      'Add DATABENTO_API_KEY to your .env file',
      'Databento is optional — only needed for futures data',
    ],
    internalCode: 'DATABENTO_NOT_CONFIGURED',
  },
  'TP-M008': {
    code: 'TP-M008',
    title: 'Databento Authentication Failed',
    message: 'Databento API authentication failed. Check your API key.',
    httpStatus: 401,
    severity: SEVERITY.HIGH,
    category: CATEGORY.MARKET_DATA,
    description: 'The Databento API rejected the provided API key.',
    possibleCauses: [
      'API key is invalid or revoked',
      'API key does not have access to the requested dataset',
    ],
    suggestedFixes: [
      'Verify the DATABENTO_API_KEY in your environment',
      'Generate a new API key from the Databento dashboard',
    ],
    internalCode: 'DATABENTO_AUTH_FAILED',
  },
  'TP-M009': {
    code: 'TP-M009',
    title: 'Databento Insufficient Credits',
    message: 'Databento API: Insufficient credits or payment required.',
    httpStatus: 402,
    severity: SEVERITY.HIGH,
    category: CATEGORY.MARKET_DATA,
    description: 'The Databento account does not have sufficient credits for the requested data.',
    possibleCauses: [
      'Databento credit balance is exhausted',
      'Payment method needs to be updated',
    ],
    suggestedFixes: [
      'Add credits to your Databento account',
      'Update payment information on databento.com',
    ],
    internalCode: 'DATABENTO_NO_CREDITS',
  },
  'TP-M010': {
    code: 'TP-M010',
    title: 'Chart Service Unavailable',
    message: 'Chart services are temporarily unavailable',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.MARKET_DATA,
    description: 'No chart data provider is available. Both primary and fallback chart services failed.',
    possibleCauses: [
      'No chart service is configured',
      'All configured chart services are down',
      'API keys for chart services are missing',
    ],
    suggestedFixes: [
      'Configure at least one chart data provider',
      'Check Finnhub and Alpha Vantage API key configuration',
      'Verify data service connectivity for chart data proxying',
    ],
    internalCode: 'CHART_SERVICE_UNAVAILABLE',
  },
  'TP-M011': {
    code: 'TP-M011',
    title: 'AI Provider Not Configured',
    message: 'AI provider is not properly configured',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.MARKET_DATA,
    description: 'The selected AI provider (OpenAI, Anthropic, Gemini, Ollama, etc.) is not properly configured.',
    possibleCauses: [
      'API key missing for the selected AI provider',
      'Unsupported AI provider selected',
      'Ollama or LM Studio URL not configured for local providers',
    ],
    suggestedFixes: [
      'Set the appropriate API key: OPENAI_API_KEY, ANTHROPIC_API_KEY, or GEMINI_API_KEY',
      'For local AI: set OLLAMA_API_URL or LOCAL_API_URL',
      'Verify the AI provider name is supported',
    ],
    internalCode: 'AI_NOT_CONFIGURED',
  },
  'TP-M012': {
    code: 'TP-M012',
    title: 'No Quote Data Available',
    message: 'No quote data available for symbol',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.MARKET_DATA,
    description: 'No price quote could be retrieved for the requested symbol.',
    possibleCauses: [
      'Symbol is invalid or delisted',
      'Market data provider does not cover this symbol',
      'Symbol format is incorrect (e.g., missing exchange prefix)',
    ],
    suggestedFixes: [
      'Verify the symbol is correct and actively traded',
      'Try an alternate symbol format',
      'Check if the symbol is covered by the configured data providers',
    ],
    internalCode: 'NO_QUOTE_DATA',
  },
  'TP-M013': {
    code: 'TP-M013',
    title: 'Dead Market Data Feed',
    message: 'Market data feed appears dead for one or more symbols',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.MARKET_DATA,
    description: 'The Global Market State detector identified one or more symbols whose price or chain data has not been updated within the expected timeframe during market hours.',
    possibleCauses: [
      'Data service poller has stopped or crashed',
      'Data service API key is rate-limited',
      'Network issues between the backend and data service',
    ],
    suggestedFixes: [
      'Check the data service health and logs',
      'Verify data service API keys and rate limits',
      'Manually trigger a market state refresh via the warmup endpoint',
    ],
    internalCode: 'DEAD_FEED',
  },

  // ═══════════════════════════════════════════════════════════════
  // BILLING & SUBSCRIPTIONS (TP-B)
  // ═══════════════════════════════════════════════════════════════
  'TP-B001': {
    code: 'TP-B001',
    title: 'Stripe Not Initialized',
    message: 'Billing not available',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.BILLING,
    description: 'Stripe is not initialized. Billing features are unavailable.',
    possibleCauses: [
      'STRIPE_SECRET_KEY not set in environment',
      'Billing is intentionally disabled for self-hosted instances',
      'Stripe initialization failed on startup',
    ],
    suggestedFixes: [
      'Set STRIPE_SECRET_KEY in your .env file',
      'If billing should be disabled, this is expected behavior',
      'Check startup logs for Stripe initialization errors',
    ],
    internalCode: 'STRIPE_NOT_INITIALIZED',
  },
  'TP-B002': {
    code: 'TP-B002',
    title: 'Stripe Webhook Verification Failed',
    message: 'Webhook signature verification failed',
    httpStatus: 400,
    severity: SEVERITY.HIGH,
    category: CATEGORY.BILLING,
    description: 'The Stripe webhook signature could not be verified. The event may be spoofed or the webhook secret is misconfigured.',
    possibleCauses: [
      'STRIPE_WEBHOOK_SECRET does not match the webhook endpoint secret in Stripe dashboard',
      'Request body was modified by a proxy',
      'Wrong webhook endpoint configured in Stripe',
    ],
    suggestedFixes: [
      'Verify STRIPE_WEBHOOK_SECRET matches your Stripe dashboard webhook endpoint secret',
      'Ensure the webhook endpoint URL is correct in Stripe',
      'Check that no proxy is modifying the request body',
    ],
    internalCode: 'STRIPE_WEBHOOK_VERIFICATION_FAILED',
  },
  'TP-B003': {
    code: 'TP-B003',
    title: 'Customer Portal Not Configured',
    message: 'Customer portal is not properly configured. Please contact support.',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.BILLING,
    description: 'The Stripe customer portal configuration is missing or invalid.',
    possibleCauses: [
      'No customer portal configuration exists in Stripe',
      'Stripe API key does not have portal permissions',
    ],
    suggestedFixes: [
      'Configure the Customer Portal in Stripe Dashboard > Settings > Billing > Customer Portal',
      'Verify the Stripe API key has the necessary permissions',
    ],
    internalCode: 'PORTAL_NOT_CONFIGURED',
  },

  // ═══════════════════════════════════════════════════════════════
  // INFRASTRUCTURE & SYSTEM (TP-I)
  // ═══════════════════════════════════════════════════════════════
  'TP-I001': {
    code: 'TP-I001',
    title: 'Internal Server Error',
    message: 'Something went wrong',
    httpStatus: 500,
    severity: SEVERITY.CRITICAL,
    category: CATEGORY.INFRA,
    description: 'An unhandled error occurred. This is a catch-all for unexpected failures.',
    possibleCauses: [
      'Unhandled exception in application code',
      'Database query failure',
      'External service returned an unexpected response',
      'Null reference or type error in business logic',
    ],
    suggestedFixes: [
      'Check server logs for the full error stack trace',
      'Check Sentry for captured exceptions',
      'Review recent code changes that may have introduced the bug',
      'Verify database connectivity and schema',
    ],
    internalCode: 'INTERNAL_SERVER_ERROR',
  },
  'TP-I002': {
    code: 'TP-I002',
    title: 'Database Connection Error',
    message: 'Database service is unreachable',
    httpStatus: 500,
    severity: SEVERITY.CRITICAL,
    category: CATEGORY.INFRA,
    description: 'Cannot establish or maintain a connection to the PostgreSQL database.',
    possibleCauses: [
      'PostgreSQL is not running',
      'DATABASE_URL or DB_HOST/DB_PORT are incorrect',
      'Connection pool is exhausted',
      'Network firewall blocking database port',
      'Database credentials are wrong',
    ],
    suggestedFixes: [
      'Verify PostgreSQL is running: pg_isready',
      'Check DATABASE_URL or individual DB_* environment variables',
      'Verify database credentials',
      'Check network/firewall rules for port 5432',
      'Increase connection pool size if under high load',
    ],
    internalCode: 'DATABASE_CONNECTION_ERROR',
  },
  'TP-I003': {
    code: 'TP-I003',
    title: 'Rate Limit Exceeded',
    message: 'Too many requests, please try again later.',
    httpStatus: 429,
    severity: SEVERITY.LOW,
    category: CATEGORY.INFRA,
    description: 'The client has sent too many requests in the configured time window.',
    possibleCauses: [
      'Automated scripts hitting the API too quickly',
      'Browser extension or tool making excessive requests',
      'Rate limit configuration is too strict',
    ],
    suggestedFixes: [
      'Wait for the retry-after period before retrying',
      'Reduce request frequency',
      'Adjust RATE_LIMIT_MAX and RATE_LIMIT_WINDOW_MS if limits are too strict',
      'Set RATE_LIMIT_ENABLED=false for self-hosted instances if appropriate',
    ],
    internalCode: 'RATE_LIMITED',
  },
  'TP-I004': {
    code: 'TP-I004',
    title: 'CORS Origin Blocked',
    message: 'Not allowed by CORS',
    httpStatus: 403,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.INFRA,
    description: 'The request origin is not in the allowed CORS origins list.',
    possibleCauses: [
      'Frontend is served from a domain not in the CORS_ORIGINS list',
      'FRONTEND_URL environment variable does not match the actual frontend URL',
      'Using a different port in development',
    ],
    suggestedFixes: [
      'Add the frontend origin to CORS_ORIGINS (comma-separated)',
      'Set FRONTEND_URL to match the actual frontend URL',
      'For development: ensure localhost:5173 is allowed',
    ],
    internalCode: 'CORS_BLOCKED',
  },
  'TP-I005': {
    code: 'TP-I005',
    title: 'Route Not Found',
    message: 'Route not found',
    httpStatus: 404,
    severity: SEVERITY.LOW,
    category: CATEGORY.INFRA,
    description: 'The requested API endpoint does not exist.',
    possibleCauses: [
      'Typo in the API URL',
      'API version mismatch',
      'Endpoint was removed or renamed',
    ],
    suggestedFixes: [
      'Check the API documentation at /api-docs',
      'Verify the URL path is correct',
    ],
    internalCode: 'ROUTE_NOT_FOUND',
  },
  'TP-I006': {
    code: 'TP-I006',
    title: 'Trading Mode Violation',
    message: 'Operation rejected: TRADING_MODE must be SIM',
    httpStatus: null,
    severity: SEVERITY.CRITICAL,
    category: CATEGORY.INFRA,
    description: 'An operation was attempted that requires SIM trading mode, but the server is configured differently.',
    possibleCauses: [
      'TRADING_MODE environment variable is not set to SIM',
      'Incorrect deployment configuration',
    ],
    suggestedFixes: [
      'Set TRADING_MODE=SIM in your environment variables',
      'This is a critical safety guard — do not bypass',
    ],
    internalCode: 'TRADING_MODE_VIOLATION',
  },
  'TP-I007': {
    code: 'TP-I007',
    title: 'Background Worker Failed',
    message: 'Background worker failed to start',
    httpStatus: null,
    severity: SEVERITY.CRITICAL,
    category: CATEGORY.INFRA,
    description: 'The background worker for trade enrichment failed to start after multiple attempts. PRO tier features will be degraded.',
    possibleCauses: [
      'Database connection issues preventing worker initialization',
      'Missing job_queue table (migration not run)',
      'Port or resource conflict',
    ],
    suggestedFixes: [
      'Check database connectivity',
      'Run pending migrations',
      'Restart the server',
      'Check server logs for specific error details',
    ],
    internalCode: 'BACKGROUND_WORKER_FAILED',
  },
  'TP-I008': {
    code: 'TP-I008',
    title: 'Email Service Error',
    message: 'Failed to send email',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.INFRA,
    description: 'An email could not be sent via the configured SMTP/email service.',
    possibleCauses: [
      'EMAIL_HOST, EMAIL_USER, or EMAIL_PASS not configured',
      'SMTP server is unreachable',
      'Email credentials are invalid',
      'SMTP port is blocked by firewall',
    ],
    suggestedFixes: [
      'Verify EMAIL_HOST, EMAIL_USER, and EMAIL_PASS in environment variables',
      'Test SMTP connectivity from the server',
      'Check firewall rules for SMTP ports (465, 587)',
    ],
    internalCode: 'EMAIL_SEND_FAILED',
  },
  'TP-I009': {
    code: 'TP-I009',
    title: 'WEBHOOK_SECRET Not Set',
    message: 'WEBHOOK_SECRET is not set — signature verification bypassed',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.INFRA,
    description: 'The WEBHOOK_SECRET environment variable is not configured. All webhook signature verification is bypassed, which is a security risk in production.',
    possibleCauses: [
      'WEBHOOK_SECRET not set in .env or environment',
      'Running in development mode without security hardening',
    ],
    suggestedFixes: [
      'Generate a strong random secret: openssl rand -hex 32',
      'Set WEBHOOK_SECRET in your .env file',
      'Configure the same secret in your TradingView alert webhook URL',
    ],
    internalCode: 'WEBHOOK_SECRET_MISSING',
  },

  // ═══════════════════════════════════════════════════════════════
  // BROKER INTEGRATIONS (TP-K)
  // ═══════════════════════════════════════════════════════════════
  'TP-K001': {
    code: 'TP-K001',
    title: 'Broker Connection Failed',
    message: 'Failed to connect to broker',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.BROKER,
    description: 'Could not establish a connection to the broker (Schwab, IBKR).',
    possibleCauses: [
      'OAuth tokens have expired',
      'Broker API is experiencing an outage',
      'Network connectivity issues',
    ],
    suggestedFixes: [
      'Re-authenticate with the broker via Settings > Broker Sync',
      'Check the broker API status page',
      'Verify network connectivity to the broker API endpoints',
    ],
    internalCode: 'BROKER_CONNECTION_FAILED',
  },
  'TP-K002': {
    code: 'TP-K002',
    title: 'IBKR Report Timeout',
    message: 'Timeout waiting for IBKR report generation',
    httpStatus: null,
    severity: SEVERITY.HIGH,
    category: CATEGORY.BROKER,
    description: 'The IBKR flex report request timed out. Reports can take several minutes to generate.',
    possibleCauses: [
      'IBKR servers are under heavy load',
      'Report request is too large (long date range)',
      'IBKR flex query token is invalid',
    ],
    suggestedFixes: [
      'Retry the sync after a few minutes',
      'Use a shorter date range for the flex report',
      'Verify the flex query token in IBKR Account Management',
    ],
    internalCode: 'IBKR_REPORT_TIMEOUT',
  },
  'TP-K003': {
    code: 'TP-K003',
    title: 'Broker Sync Failed',
    message: 'Failed to sync trades from broker',
    httpStatus: null,
    severity: SEVERITY.MEDIUM,
    category: CATEGORY.BROKER,
    description: 'An error occurred while syncing trade data from the connected broker.',
    possibleCauses: [
      'Broker API returned unexpected data format',
      'OAuth tokens expired mid-sync',
      'Broker API rate limit exceeded',
    ],
    suggestedFixes: [
      'Re-authenticate with the broker',
      'Check broker sync logs for specific errors',
      'Try a manual sync with a shorter date range',
    ],
    internalCode: 'BROKER_SYNC_FAILED',
  },
};

function getErrorByInternalCode(internalCode) {
  return Object.values(ERROR_CATALOG).find(e => e.internalCode === internalCode) || null;
}

function getErrorsByCategory(categoryKey) {
  const cat = CATEGORY[categoryKey];
  if (!cat) return [];
  return Object.values(ERROR_CATALOG).filter(e => e.category.key === cat.key);
}

function getErrorsBySeverity(severity) {
  return Object.values(ERROR_CATALOG).filter(e => e.severity === severity);
}

function getAllErrors() {
  return Object.values(ERROR_CATALOG);
}

function getCategories() {
  return Object.entries(CATEGORY).map(([key, val]) => ({
    key,
    ...val,
    count: Object.values(ERROR_CATALOG).filter(e => e.category.key === val.key).length,
  }));
}

function getSeveritySummary() {
  const all = Object.values(ERROR_CATALOG);
  return {
    critical: all.filter(e => e.severity === SEVERITY.CRITICAL).length,
    high: all.filter(e => e.severity === SEVERITY.HIGH).length,
    medium: all.filter(e => e.severity === SEVERITY.MEDIUM).length,
    low: all.filter(e => e.severity === SEVERITY.LOW).length,
    total: all.length,
  };
}

module.exports = {
  SEVERITY,
  CATEGORY,
  ERROR_CATALOG,
  getErrorByInternalCode,
  getErrorsByCategory,
  getErrorsBySeverity,
  getAllErrors,
  getCategories,
  getSeveritySummary,
};
